import {
  Utensils,
  UtensilsCrossed,
  CookingPot,
  ChefHat,
  Coffee,
  CupSoda,
  Beer,
  Wine,
  Pizza,
  Sandwich,
  Salad,
  Soup,
  Beef,
  Fish,
  Croissant,
  Cake,
  IceCreamCone,
  Popcorn,
  Apple,
  Carrot,
  Milk,
  ShoppingBasket,
  ShoppingCart,
  ShoppingBag,
  Store,
  Tag,
  Package,
  Gift,
  Shirt,
  Footprints,
  Watch,
  Glasses,
  Gem,
  Scissors,
  House,
  HousePlug,
  Plug,
  Zap,
  Flame,
  Droplet,
  Wifi,
  Smartphone,
  Phone,
  Tv,
  Lightbulb,
  Wrench,
  Hammer,
  PaintRoller,
  Sofa,
  BedDouble,
  WashingMachine,
  Trash2,
  Key,
  Umbrella,
  Car,
  CarFront,
  Bus,
  TrainFront,
  TramFront,
  Bike,
  Fuel,
  CircleParking,
  Plane,
  Ship,
  Caravan,
  TrafficCone,
  Luggage,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  BriefcaseMedical,
  Hospital,
  Brain,
  Eye,
  Dumbbell,
  Activity,
  Clapperboard,
  Music,
  Headphones,
  Guitar,
  Gamepad2,
  Dices,
  Ticket,
  Drama,
  PartyPopper,
  Palette,
  Camera,
  Book,
  BookOpen,
  Tent,
  Trees,
  Mountain,
  Waves,
  Sparkles,
  Wallet,
  PiggyBank,
  Banknote,
  Coins,
  CreditCard,
  Landmark,
  Receipt,
  HandCoins,
  Percent,
  Scale,
  Calculator,
  TrendingUp,
  ChartPie,
  Briefcase,
  Building2,
  FileText,
  Users,
  Baby,
  Heart,
  Handshake,
  Dog,
  Cat,
  PawPrint,
  GraduationCap,
  Church,
  Shield,
  Flower2,
  Sprout,
  Cigarette,
  MapPin,
  Calendar,
  Mail,
  Star,
  Repeat,
  CircleEllipsis,
  CirclePlus,
  Circle,
  type LucideIcon,
} from "lucide-react";
import { CATEGORY_ICONS, type CategoryIcon } from "@/lib/validation/category";

/**
 * Maps every `CategoryIcon` string (src/lib/validation/category.ts) to its
 * Lucide component. `Record<CategoryIcon, LucideIcon>` means TypeScript
 * fails this file to compile if the two lists ever drift apart, in either
 * direction — a missing key or an extra one is a type error, not a runtime
 * surprise the first time someone picks the icon that isn't wired up.
 *
 * A separate module from src/lib/validation/category.ts's `CATEGORY_ICONS`
 * string list (rather than merged into it) so that module stays free of a
 * `lucide-react`/React import, and so this one can be imported by Server
 * Components rendering static icon markup without pulling in zod.
 */
export const CATEGORY_ICON_COMPONENTS: Record<CategoryIcon, LucideIcon> = {
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  "cooking-pot": CookingPot,
  "chef-hat": ChefHat,
  coffee: Coffee,
  "cup-soda": CupSoda,
  beer: Beer,
  wine: Wine,
  pizza: Pizza,
  sandwich: Sandwich,
  salad: Salad,
  soup: Soup,
  beef: Beef,
  fish: Fish,
  croissant: Croissant,
  cake: Cake,
  "ice-cream-cone": IceCreamCone,
  popcorn: Popcorn,
  apple: Apple,
  carrot: Carrot,
  milk: Milk,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  store: Store,
  tag: Tag,
  package: Package,
  gift: Gift,
  shirt: Shirt,
  footprints: Footprints,
  watch: Watch,
  glasses: Glasses,
  gem: Gem,
  scissors: Scissors,
  house: House,
  "house-plug": HousePlug,
  plug: Plug,
  zap: Zap,
  flame: Flame,
  droplet: Droplet,
  wifi: Wifi,
  smartphone: Smartphone,
  phone: Phone,
  tv: Tv,
  lightbulb: Lightbulb,
  wrench: Wrench,
  hammer: Hammer,
  "paint-roller": PaintRoller,
  sofa: Sofa,
  "bed-double": BedDouble,
  "washing-machine": WashingMachine,
  trash2: Trash2,
  key: Key,
  umbrella: Umbrella,
  car: Car,
  "car-front": CarFront,
  bus: Bus,
  "train-front": TrainFront,
  "tram-front": TramFront,
  bike: Bike,
  fuel: Fuel,
  "circle-parking": CircleParking,
  plane: Plane,
  ship: Ship,
  caravan: Caravan,
  "traffic-cone": TrafficCone,
  luggage: Luggage,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  "briefcase-medical": BriefcaseMedical,
  hospital: Hospital,
  brain: Brain,
  eye: Eye,
  dumbbell: Dumbbell,
  activity: Activity,
  clapperboard: Clapperboard,
  music: Music,
  headphones: Headphones,
  guitar: Guitar,
  gamepad2: Gamepad2,
  dices: Dices,
  ticket: Ticket,
  drama: Drama,
  "party-popper": PartyPopper,
  palette: Palette,
  camera: Camera,
  book: Book,
  "book-open": BookOpen,
  tent: Tent,
  trees: Trees,
  mountain: Mountain,
  waves: Waves,
  sparkles: Sparkles,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  banknote: Banknote,
  coins: Coins,
  "credit-card": CreditCard,
  landmark: Landmark,
  receipt: Receipt,
  "hand-coins": HandCoins,
  percent: Percent,
  scale: Scale,
  calculator: Calculator,
  "trending-up": TrendingUp,
  "chart-pie": ChartPie,
  briefcase: Briefcase,
  building2: Building2,
  "file-text": FileText,
  users: Users,
  baby: Baby,
  heart: Heart,
  handshake: Handshake,
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  "graduation-cap": GraduationCap,
  church: Church,
  shield: Shield,
  flower2: Flower2,
  sprout: Sprout,
  cigarette: Cigarette,
  "map-pin": MapPin,
  calendar: Calendar,
  mail: Mail,
  star: Star,
  repeat: Repeat,
  "circle-ellipsis": CircleEllipsis,
  "circle-plus": CirclePlus,
  circle: Circle,
};

/**
 * The same icons, split into the labelled groups the picker renders. At 132
 * icons a flat wrap row is a wall of glyphs; grouping is what makes the set
 * navigable.
 *
 * `satisfies` rather than a plain annotation so each `icons` array keeps its
 * literal type — that is what lets `ICONS_IN_GROUPS` below be compared
 * against `CATEGORY_ICONS` at compile time. The two checks that follow prove
 * the grouping is a partition of the enum: nothing missing, nothing
 * duplicated, nothing invented. Without them a new icon could be added to
 * the enum and silently never appear in the UI — the picker would look
 * complete while offering fewer icons than the app accepts.
 */
export const CATEGORY_ICON_GROUPS = [
  {
    label: "Food & drink",
    icons: ["utensils", "utensils-crossed", "cooking-pot", "chef-hat", "coffee", "cup-soda", "beer", "wine", "pizza", "sandwich", "salad", "soup", "beef", "fish", "croissant", "cake", "ice-cream-cone", "popcorn", "apple", "carrot", "milk"],
  },
  {
    label: "Shopping",
    icons: ["shopping-basket", "shopping-cart", "shopping-bag", "store", "tag", "package", "gift", "shirt", "footprints", "watch", "glasses", "gem", "scissors"],
  },
  {
    label: "Home & bills",
    icons: ["house", "house-plug", "plug", "zap", "flame", "droplet", "wifi", "smartphone", "phone", "tv", "lightbulb", "wrench", "hammer", "paint-roller", "sofa", "bed-double", "washing-machine", "trash2", "key", "umbrella"],
  },
  {
    label: "Transport",
    icons: ["car", "car-front", "bus", "train-front", "tram-front", "bike", "fuel", "circle-parking", "plane", "ship", "caravan", "traffic-cone", "luggage"],
  },
  {
    label: "Health & fitness",
    icons: ["heart-pulse", "stethoscope", "pill", "syringe", "briefcase-medical", "hospital", "brain", "eye", "dumbbell", "activity"],
  },
  {
    label: "Leisure",
    icons: ["clapperboard", "music", "headphones", "guitar", "gamepad2", "dices", "ticket", "drama", "party-popper", "palette", "camera", "book", "book-open", "tent", "trees", "mountain", "waves", "sparkles"],
  },
  {
    label: "Money & work",
    icons: ["wallet", "piggy-bank", "banknote", "coins", "credit-card", "landmark", "receipt", "hand-coins", "percent", "scale", "calculator", "trending-up", "chart-pie", "briefcase", "building2", "file-text"],
  },
  {
    label: "People & other",
    icons: ["users", "baby", "heart", "handshake", "dog", "cat", "paw-print", "graduation-cap", "church", "shield", "flower2", "sprout", "cigarette", "map-pin", "calendar", "mail", "star", "repeat", "circle-ellipsis", "circle-plus", "circle"],
  },
] as const satisfies readonly { label: string; icons: readonly CategoryIcon[] }[];

const ICONS_IN_GROUPS = CATEGORY_ICON_GROUPS.flatMap((g) => g.icons as readonly CategoryIcon[]);

/** Every enum member is placed in exactly one group. Throws at import time,
 *  which in practice means the first render in dev and the build in CI. */
if (process.env.NODE_ENV !== "production") {
  const grouped = new Set(ICONS_IN_GROUPS);
  if (grouped.size !== ICONS_IN_GROUPS.length) {
    throw new Error("CATEGORY_ICON_GROUPS lists an icon more than once");
  }
  const missing = CATEGORY_ICONS.filter((i) => !grouped.has(i));
  if (missing.length) {
    throw new Error(`CATEGORY_ICON_GROUPS is missing: ${missing.join(", ")}`);
  }
}
