import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the local Supabase CLI (gitignored via supabase/.gitignore);
    // not project source, so it shouldn't be linted.
    "supabase/.temp/**",
    "supabase/.branches/**",
    // Agent worktrees created inside the repo by the harness — a second
    // checkout of this same project, not source to lint. Without this, its
    // files are linted twice and reported against paths that do not exist
    // from a consumer's point of view.
    ".claude/worktrees/**",
  ]),
]);

export default eslintConfig;
