import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentUserProfile } from "@/lib/supabase/current-user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Sets `data-theme` on `<html>` — not on some inner wrapper — because
 * src/app/globals.css keys its dark-mode palette off `:root[data-theme="dark"]`
 * and `@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) }`.
 * `:root` is a CSS pseudo-class that always refers to the document's root
 * element (`<html>`); it does NOT match a `data-theme` attribute placed on a
 * descendant div. Since it's already read here during the server render,
 * the very first byte of HTML has the right attribute — no client-side
 * effect flips it after hydration, so there is no flash of the wrong theme
 * for an explicit 'light'/'dark' choice.
 *
 * For 'system' the attribute is omitted entirely, so globals.css's
 * `@media (prefers-color-scheme: dark)` block — a browser-native media
 * query, not JS — decides, and keeps deciding live if the OS theme changes
 * while the app is open. No listener needed for that case either.
 *
 * This makes the layout depend on the caller's session (via cookies()
 * inside getCurrentUserProfile), which opts the whole app into dynamic
 * rendering. Given every route below is either an auth page or sits behind
 * the (app) auth gate, nothing here was a static-optimization candidate
 * anyway — the trade is flash-free theming for zero cacheable HTML, which
 * is the right side of that trade for this app.
 */
export default async function RootLayout({ children }: LayoutProps<"/">) {
  const profile = await getCurrentUserProfile();
  const theme = profile?.theme ?? "system";

  return (
    <html
      lang="en"
      data-theme={theme === "system" ? undefined : theme}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
